// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPaaqBbMQ6tQUt1hlhGeiDrejovs51hm0',
    appId: '1:1076172285851:web:4b158d8f7b8e159054e33e',
    messagingSenderId: '1076172285851',
    projectId: 'chat-demo-6728b',
    authDomain: 'chat-demo-6728b.firebaseapp.com',
    storageBucket: 'chat-demo-6728b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNzwe9vFqejed1w9UasaPpZIAxl0EVWJk',
    appId: '1:1076172285851:android:93d9d2f2b6d2652a54e33e',
    messagingSenderId: '1076172285851',
    projectId: 'chat-demo-6728b',
    storageBucket: 'chat-demo-6728b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-j1vGa6xJt4m2GR_6Bae1aUP8xmrFGzY',
    appId: '1:1076172285851:ios:b402b575ccdc4b0654e33e',
    messagingSenderId: '1076172285851',
    projectId: 'chat-demo-6728b',
    storageBucket: 'chat-demo-6728b.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-j1vGa6xJt4m2GR_6Bae1aUP8xmrFGzY',
    appId: '1:1076172285851:ios:b402b575ccdc4b0654e33e',
    messagingSenderId: '1076172285851',
    projectId: 'chat-demo-6728b',
    storageBucket: 'chat-demo-6728b.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPaaqBbMQ6tQUt1hlhGeiDrejovs51hm0',
    appId: '1:1076172285851:web:fbb1c976f420653c54e33e',
    messagingSenderId: '1076172285851',
    projectId: 'chat-demo-6728b',
    authDomain: 'chat-demo-6728b.firebaseapp.com',
    storageBucket: 'chat-demo-6728b.appspot.com',
  );
}
